version: "3"
services:
  web:
    # Si has subido tu imagen a Docker Hub pon la etiqueta apropiada.
    image: antsala/hello_container  
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8080"
    networks:
      - webnet
networks:
  webnet: