apiVersion: v1
kind: Service
metadata:
  name: "external-web"
spec:
  ports:
    -
#      name: "apache"
      protocol: "TCP"
      port: 80
      targetPort: 80 
---
  apiVersion: v1
  kind: Endpoints
  metadata:
    name: "external-web" 
  subsets: 
    -
      addresses:
        -
          ip: "192.168.1.38" # Aquí habría que poner la IP del servicio externo.
      ports:
        -
          port: 80 
 #         name: "apache"