apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
        server: server1
  template:
    metadata:
      labels:
        app: web-server
        server: server1
    spec:
      containers:
        - name: nginx-1
          image: nginx:1.19.6-alpine
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthy.html
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: index
              mountPath: /tmp/lab-65-B-index1.html
              subPath: lab-65-B-index1.html
            - name: healthy
              mountPath: /tmp/lab-65-B-healthy.html
              subPath: lab-65-B-healthy.html
          command: ["/bin/sh", "-c"]
          args: ["cp /tmp/lab-65-B-index1.html /usr/share/nginx/html/index.html; cp /tmp/lab-65-B-healthy.html /usr/share/nginx/html/healthy.html; nginx; sleep inf"]
      volumes:
        - name: index
          configMap:
            name: server1
        - name: healthy
          configMap:
            name: healthy
        - name: html
          emptyDir: {}