version: "3"
services:
  sinatra:  # Este es el frontend Sinatra.
    # Si has subido tu imagen a Docker Hub pon la etiqueta apropiada.
    image: antsala/sinatra
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:4567"
    volumes:
      - .:/opt/webapp  # Ojo, '.' equivale a $PWD en 'docker run...'
    networks:
      - app

  db:  # Este es el Backend Redis.
    # Si has subido tu imagen a Docker Hub pon la etiqueta apropiada.
    image: antsala/redis
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    networks:
      - app
    
networks:
  app: