apiVersion: v1
kind: Service
metadata:
  name: hello-container-service
spec:
  type: LoadBalancer
  selector:
    app: helloContainer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000

