apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: code lab-25-B-mongodb-secret-initial.yaml
  mongo-root-password: <Poner aquí el PASSWORD de usuario codificado en Base64>
