apiVersion: v1
kind: Service
metadata:
  name: frontend-load-balancer
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
