apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: <Poner aquí el NOMBRE de usuario codificado en Base64>
  password: <Poner aquí el PASSWORD de usuario codificado en Base64>
  