apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: <Poner aquí el NOMBRE DE USUARIO codificado en base64>
  mongo-root-password: <Poner aquí el PASSWORD DE USUARIO codificado en base64>
